name: Container

on:
  push:
    paths:
      - .github/workflows/container.yml
      - Dockerfile
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        uses: paulhatch/semantic-version@v4.0.2
        id: version
        with:
          tag_prefix: v
          major_pattern: /breaking/
          minor_pattern: /feat(ure)?/
          format: "${major}.${minor}.${patch}"
          change_path: Dockerfile
          short_tags: false
      - name: Name
        uses: ashley-taylor/regex-property-action@1.2
        id: name
        with:
          value: ${{ github.event.repository.name }}
          regex: ^docker-
          replacement: ""
      - name: Release
        uses: ncipollo/release-action@v1
        if: steps.version.outputs.changed
        with:
          allowUpdates: true
          tag: ${{ steps.version.outputs.version_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
      - name: Build
        if: steps.version.outputs.changed
        uses: aevea/action-kaniko@master
        with:
          image: ${{ github.repository_owner }}/${{ steps.name.outputs.value }}
          tag: ${{ steps.version.outputs.version_tag }}
          tag_with_latest: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_PAT }}
          extra_args: --label org.opencontainers.image.source=https://github.com/${{ github.repository }}
