name: Release

on:
  push:
    branches:
      - main

jobs:

  tag:
    name: Bump tag
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.tag.outputs.changelog }}
      version: ${{ steps.tag.outputs.new_version }}
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag
        with:
          github_token: ${{ secrets.github_token }}

  container:
    name: Build and push container
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Name
        uses: ashley-taylor/regex-property-action@1.2
        id: name
        with:
          value: ${{ github.repository }}
          regex: /docker-
          replacement: "/"
      - name: Log in
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.name.outputs.value }}:${{ needs.tag.outputs.tag }}
            ghcr.io/${{ steps.name.outputs.value }}:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ needs.tag.outputs.tag }}
            org.opencontainers.image.revision=${{ github.sha }}

  chart:
    name: Build and push chart
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Name
        id: name
        run: echo "::set-output name=chart::$(ls charts/)"
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Modify Chart.yaml
        run: |
          sed --in-place 's/version: .*/version: ${{needs.tag.outputs.version}}/' charts/${{ steps.name.outputs.chart }}/Chart.yaml
          sed --in-place 's/appVersion: .*/appVersion: ${{needs.tag.outputs.tag}}/' charts/${{ steps.name.outputs.chart }}/Chart.yaml
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Build and push chart
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.github_token }}"
          CR_SKIP_EXISTING: true

  release:
    name: Create tag and release
    runs-on: ubuntu-latest
    needs:
      - tag
      - container
      - chart
    steps:
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.tag }}
          name: Release ${{ needs.tag.outputs.tag }}
          body: ${{ needs.tag.outputs.changelog }}
