name: Release

on:
  push:
    paths:
      - .github/workflows/release.yml
      - Dockerfile
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and tag
        uses: mathieudutour/github-tag-action@v6.0
        id: version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Name
        uses: ashley-taylor/regex-property-action@1.2
        id: name
        with:
          value: ${{ github.repository }}
          regex: /docker-
          replacement: "/"
      - name: Log in
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.name.outputs.value }}:${{ steps.version.outputs.new_tag }}
            ghcr.io/${{ steps.name.outputs.value }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.new_tag }}
          name: Release ${{ steps.version.outputs.new_tag }}
          body: ${{ steps.version.outputs.changelog }}
