name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag
        uses: hennejg/github-tag-action@v4.3.1
        id: semver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Release
        if: steps.semver.outputs.new_tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: ${{ steps.semver.outputs.changelog }}
          tag: ${{ steps.semver.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: steps.semver.outputs.new_tag
        uses: aevea/action-kaniko@master
        with:
          image: ${{ github.repository_owner }}/qemu-guest-agent
          tag: ${{ steps.semver.outputs.new_tag }}
          tag_with_latest: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_PAT }}
          extra_args: --label org.opencontainers.image.source=https://github.com/${{ github.repository }}
