name: Test Helm chart

on: 
  pull_request:
    paths:
      - charts/**

jobs:
  test:
    name: Test Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
      - name: Run chart-testing
        run: ct lint --all --check-version-increment=false
